sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: '2.6'
    env: TOX_ENV=py26
  - python: '2.7'
    env: TOX_ENV=py27
  - python: '3.5'
    env: TOX_ENV=static
  - python: '3.5'
    env: TOX_ENV=cov-travis DEPLOY=1
 - python: "3.5"
   env: TOX_ENV=docs
   script: tox -e $TOX_ENV
after_success:
  - test $TOX_ENV = docs && scripts/push-docs
script: tox -e $TOX_ENV
deploy:
  provider: pypi
  user: content-delivery-release-bot
  password:
    secure: DuvnB65BjZyrTbDXynttGoJd9Gh+3WMK7N3u88JSJ8CKTHHJMcxli5sO9wmyQEtPoW9XQe+zyHzEq0g3Let4L9eCeYAqK5fOemo2JiVNhBFcOUJUDQfsxW8dfaOrBfuiTG1dqxssAOMGdDx1dMXy7kjfMKqRGGo7sLfVOIV78tQo+qClnIMUJgAG8+X4G7FgXOBtvZ7m0egNAE5ElaNwlKOybC8P6nibkzvuNjQoQKtC1JWDoW2MhL7juY+vX+8FOlBatqB5zbEzM843RY7uLQjg8avYD/q5OJYD738nxZVkCTxU3KEbfBvwAz4f5gXyyQ3C/gzfrezepwEyNMzFE2EbayMFY6hYoAkmt2UOW0WiM5bD786EbFPXeoyeI5x02VQkjtWxASKTgmAPCuBqKArWHvmm04Qh6mRjeuBygb1+WF0HnWmUbvknTfjz5nvjDEtg0/mV0IVRpnFkpGC1gtElUusgc6PdsvObX+LM9rukdeO1FACq0WqTI8Jmdgfs9Zd5SZhQwoZmFnHCFti8AnSqlPH98OcoqF6EbQ74fINH8BLLuyH6aS7HLtMD2orYyedEnUFU4/lRGG2qNvaxkm6ZYOMuAZDmkJq9O/oa9lOl5EgHh/GynG6AwT+iAd35NHXQrmVz76DdyFQIP4Th5jmXCPjQAr9nvdbopEWr1p0=
  on:
    tags: true
    condition: "$DEPLOY = 1"
  skip_existing: true
